version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    container_name: react-events
    command: serve -s dist -l 3000
    restart: unless-stopped
    ports:
      - '3000:3000'
