version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: react-events-dev
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./src:/usr/src/app/src
