version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: react-events-client-dev
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src

  api:
    volumes:
      - ./api/src:/usr/src/app/src

  nginx:
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/conf.d/nginx.conf