version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: react-events-client
    command: serve -s dist -l 3000
    restart: unless-stopped
    ports:
      - '3000:3000'
