version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: react-events-client
    command: serve -s dist -l 3000
    restart: unless-stopped
    depends_on:
      - api
    environment:
      - NGINX_PORT=80
      - VITE_DOCKER_API_URL=/api/
    networks:
      - react-events-network

  api:
    build: ./api
    container_name: react-events-api
    restart: unless-stopped
    command: npm start
    environment:
      - PORT=3001
    networks:
      - react-events-network

  nginx:
    image: nginx:stable-alpine
    container_name: react-events-nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
      - client
    networks:
      - react-events-network

networks:
  react-events-network:
    driver: bridge