version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: react-events-dev
    command: npm run dev
    stdin_open: true
    tty: true
    volumes:
      - ./client/src:/usr/src/app/src
